[package]
name = "chomsky-context"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Context and environment management for Chomsky framework"
repository = "https://github.com/nyar-vm/project-chomsky/tree/main/packages/chomsky-context"
homepage = "https://gaia-assembly.netlify.app/chomsky/context/"

[dependencies]
chomsky-uir = { workspace = true }
