[package]
name = "chomsky-rules"
description = "Optimization rules collection for Chomsky framework"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = "https://github.com/nyar-vm/project-chomsky/tree/main/packages/chomsky-rules"
homepage = "https://gaia-assembly.netlify.app/chomsky/rules/"

[dependencies]
chomsky-uir = { workspace = true }
chomsky-rule-engine = { workspace = true }
chomsky-types = { workspace = true }
