[package]
name = "chomsky-linker"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Linker for E-Graphs, handling cross-module references and fusion in Chomsky framework"
repository = "https://github.com/nyar-vm/project-chomsky/tree/main/packages/chomsky-linker"
homepage = "https://gaia-assembly.netlify.app/chomsky/linker/"

[dependencies]
chomsky-uir = { workspace = true }
chomsky-types = { workspace = true }
hashbrown = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
