[package]
name = "chomsky-rule-engine"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Rewrite rule engine for Chomsky optimization framework"
repository = "https://github.com/nyar-vm/project-chomsky/tree/main/packages/chomsky-rule-engine"
homepage = "https://gaia-assembly.netlify.app/chomsky/rule-engine/"

[dependencies]
chomsky-uir = { workspace = true }
