name: Rust

on:
  push:
    branches: [ master, dev, main ]
  pull_request:
    branches: [ master, dev, main ]

jobs:
  check:
    name: Check (${{ matrix.os }}, ${{ matrix.feature_set.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        feature_set:
          - { name: "No Features", flags: "--no-default-features" }
          - { name: "Default Features", flags: "" }
          - { name: "All Features", flags: "--all-features" }
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Cargo Check
        run: cargo check ${{ matrix.feature_set.flags }}
        env:
          RUSTFLAGS: -A warnings

  release:
    name: Release (${{ matrix.os }})
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Build Release
        run: cargo build --release
        env:
          RUSTFLAGS: -A warnings
      # - name: Run Tests
      #   run: cargo test --release
      #   env:
      #     RUSTFLAGS: -A warnings
